openapi: 3.1.0
info:
  title: Growth Engineering Youtube Test
  version: 1.0.0
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  description: OpenAPI declarations for Growth Engineering youtube test
  summary: OpenAPI declarations for Growth Engineering youtube test
  contact:
    name: Oğuz Özcan
    email: hello@oguzozcan.com
servers:
  - url: 'https://localhost:5001'
    description: Local
  - url: 'https://geyt.ml'
    description: Production
paths: {}
components:
  schemas: {}
tags:
  - name: Youtube
